Conversion example for tensile test
materialdigital/eln2rdf pull request #3
Opened 2024-10-09 08:44 UTC by jehona-kryeziu

2024-10-09 15:29 UTC, schaarj requested changes
I would add a little bit more markdown between the code blocks. Furthermore I would try to keep the example code as minimal as possible loggers, and try catch blocks are imho not really needed here

2024-10-09 15:29 UTC, schaarj commented on example.zip
the way  the group is included does not represent the way it is expected in elabFTW exports, where it is typically coming from `item_links` or sth. similar if I recall correctly
Also, I would name the example file `tensile_test_example.eln` and put it with the Jupyter notebook in a subfolder (e.g. "examples" or "sample_data")

2024-10-09 15:29 UTC, schaarj commented on tensile_test.ipynb
> +    "This notebook uses an example of the data which is synthetic, but that fits the format of the data derived from the experiments. The goal is to see how the scripts convert the data from the comp
add a little bit more markdown like a heading

2024-10-11 08:23 UTC, jehona-kryeziu commented on example.zip
now we have the exact format for the json data, and all the files are moved to "examples" subfolder and also the eln file is named accordingly

2024-10-11 13:45 UTC, schaarj approved these changes

2024-10-11 13:45 UTC, merged